I started the day with events no longer syncing again, and after a few manipulations it worked again... I'm still not sure 100% of what happens every time, between reseting the Local Devchain, and creating new sync events

Now, the image still is not displaying:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
```

is the error that I'm getting, while I'm correctly getting the image url from the token URI : `the image is "ipfs://bafybeibg7mpzkn3szrx2dp37tdudmtqnu2nfogr2pnjz5ewu52kshgxehu"`

I'll try with updating the SDKfor the newest version, see if that changes anything (2.6.3)
